### ISSUE TITLE
Add status badges to the README

### ISSUE THREAD

**Issue by sverweij** [sverweij/compact-yarn-audit#1]
## Current situation

The README doesn't show badges on build status, package security or npm version or license. 

## Desired situation

The top of the README.md includes a row of these badges so it's easier to see for casual onlookers in what shape compact-yarn-audit is.

- current build status:
```markdown
[![GitHub Workflow Status](https://github.com/sverweij/compact-yarn-audit/actions/workflows/lint-and-test.yml/badge.svg)](https://github.com/sverweij/compact-yarn-audit/actions/workflows/lint-and-test.yml)
```

- known vulnerabilities (from snyk.io):
```markdown
[![Known Vulnerabilities](https://snyk.io/test/github/sverweij/compact-yarn-audit/badge.svg?targetFile=package.json)](https://snyk.io/test/github/sverweij/compact-yarn-audit?targetFile=package.json)
```

- latest version stable version on npm:
```markdown
[![npm stable version](https://img.shields.io/npm/v/compact-yarn-audit.svg?logo=npm)](https://npmjs.com/package/compact-yarn-audit)
```

- license:
```markdown
[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](LICENSE)
```

**Comment by SubhamChoudhury** [comment]
Hi, I would like to work on it, can you assign it to me please?
